# -*- coding: utf-8 -*-
"""kadai_005

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CoVVc-cKZbzDYQHMuMrAsRfR4VY-sRgI
"""

top_side=10
bottom_side=20
height=5

area = ((top_side + bottom_side) * height) / 2

print(f"{area}㎠")

