# -*- coding: utf-8 -*-
"""kadai_015

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kG8YVf8vnNdXslwBu057RlKRjucuiuS7
"""

class Human:
#初期化＆代入
  def __init__(self, name, age):
    self.name = name
    self.age = age
#出力メソッドの設定
  def printinfo(self):
      print(self.name)
      print(self.age)
#humanのインスタンス化
human = Human("侍太郎", 36)

#インスタンス内メソッドの呼び出し
human.printinfo()

