# -*- coding: utf-8 -*-
"""kadai_017

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1I4XK4-MJgWaATTJvwI5ycl8eCFKxNmml
"""

class Human:
  #初期化＆代入
  def __init__(self, name, age):
    self.name = name
    self.age = age

    #出力メソッドの設定
  def check_adult(self):
    if self.age < 20:
      print(f"{self.name}は大人です")
    else:
      print(f"{self.name}は大人ではありません")

#humanのインスタンス化
human1 = Human("侍太郎", 36)
human2 = Human("侍花子", 19)
human3 = Human("侍次郎", 21)

#インスタンスをリストに追加
human_list = [human1, human2, human3]

#リストの数だけメソッドを呼び出し
for human in human_list:
    human.check_adult()

