# -*- coding: utf-8 -*-
"""kadai_013

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dmCkSkUPLvdOBtp7OhRnSOI2abPUbYtC
"""

def calculate_total(price, tax):
  total=price*(1+tax)

  print(f"{total}円")

calculate_total(500,0.1)

