# -*- coding: utf-8 -*-
"""kadai_011

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ljOe3akoWDiBDi4uVFccdnyqUJJJ9Urd
"""

array = ["水","金","地","火","木","土","天","海","冥"]

for i in array:
  print(i)

#インデックスを初期化
i = 0

#配列の長さまで繰り返す
while i < len(array):
  print(array[i])
  i +=1

