# -*- coding: utf-8 -*-
"""kadai_008

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PEvqXeMXCrm5LtyIQawl8YqFc4y-TEks
"""

var = 30

if var % 3 == 0 and var % 5 == 0:
  print("FizzBuzz")
elif var % 3 == 0:
  print("Fizz")
elif var % 5 == 0:
  print("Buzz")

else:
  print(var)

